### ISSUE TITLE
One or two FP-themed meetups in August/September/October 2017

### ISSUE THREAD

**Issue by keleshev** [mads-hartmann/polyglots.dk#12]
SimCorp can host one or two meetups during on the following days:

* August: 22, 23, 24
* September: 12, 13, 21
* October: 10, 11, 12, 17, 18

**Comment by keleshev** [comment]
Here's a doodle for _speakers_: http://doodle.com/poll/y3hqvqza7iprt6pq

**Comment by keleshev** [comment]
I suggest that we try organizing the meetup using GitHub issues. I have seen it work quite well for Copenhagen Elm meetup: https://github.com/elmcph/elmcph/issues?q=is%3Aissue+is%3Aclosed

**Comment by Leonidas-from-XIV** [comment]
Sounds good, I've added myself to the Doodle.

**Comment by Leonidas-from-XIV** [comment]
I'll close this one for now since it passed, but I like the idea and would want to use this approach for the next meetup 😄
