### ISSUE TITLE
October special with Gary Bernhardt

### ISSUE THREAD

**Issue by keleshev** [mads-hartmann/polyglots.dk#6]
@mads379, @JKrag you know [Gary Bernhardt](https://twitter.com/garybernhardt)? He's a big Pythonista/Rubyista. He's now in Malmø, so I suggested him to meetup. He is going to give a talk (title is pending) on 27th of October (Monday). Technically this is not a Polyglot event, since we are (probably) not going to talk about any specific languages, unless accidentally, so I'm going to frame it as a Python special. However, could I get 1 or 2 newsletters out about this event from the Polyglot newsletter? I'm pretty sure it could be interesting to our subscribers. @mads379 are you in charge of the newsletter account?

**Comment by Leonidas-from-XIV** [comment]
I'll close this for now. But if you ever hear about any more "known" programmers visiting the region, please don't hesitate to open new tickets with ideas! 👍
